version: '3'

networks:
  kafka:
    driver: bridge

volumes:
  zookeeper1:
    driver: local
  zookeeper2:
    driver: local
  zookeeper3:
    driver: local
  kafka1:
    driver: local
  kafka2:
    driver: local
  kafka3:
    driver: local
    
services:
  zookeeper1:
    image: zookeeper:3.5.8
    container_name: zookeeper1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper1:/data
    networks:
      - kafka
      
  zookeeper2:
    image: zookeeper:3.5.8
    container_name: zookeeper2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - zookeeper2:/data
    networks:
      - kafka
      
  zookeeper3:
    image: zookeeper:3.5.8
    container_name: zookeeper3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - zookeeper3:/data
    networks:
      - kafka
      
  kafka1:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka1
    restart: always
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 19092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.77.133
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka1:/kafka
    networks:
      - kafka
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      
  kafka2:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka2
    restart: always
    ports:
      - "29092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 29092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.77.133
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka2:/kafka
    networks:
      - kafka
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      
  kafka3:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka3
    restart: always
    ports:
      - "39092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 39092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.77.133
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 503
      KAFKA_offsets_topic_replication_factor: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka3:/kafka
    networks:
      - kafka
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
